name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get /HolismHolding/Infra
        run: |
          sudo mkdir /HolismHolding
          sudo chmod -R 777 /HolismHolding
          cd /HolismHolding
          git clone https://github.com/HolismHolding/Infra
      - name: Get /Nefcanto/Nefcanto
        run: |
          sudo mkdir /Nefcanto
          sudo chmod -R 777 /Nefcanto
          cd /Nefcanto
          git clone https://github.com/Nefcanto/Nefcanto
      - name: Build production docker
        run: /HolismHolding/Infra/Build.sh
